"""Build/check the Korean annotated reference. It is never a Unity runtime asset.
Default: verify. --patch: emit an apply_patch patch (does not write files itself).
"""
import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = Path("Assets/CursorHunter/Data/Resources/GameData/game-data.en.json")
OUTPUT = Path("docs/collaboration/game-data.ko.reference.json")
KEYS_OUTPUT = Path("docs/collaboration/game-data.ko.keys.json")

LABELS = {
    "behaviorType": "몬스터 행동 특성",
    "prefabKey": "외형 프리팹 키",
    "documentVersion": "전체 문서 버전",
    "locale": "원본 데이터 언어",
    "description": "설명",
    "information": "전투 기본 정보",
    "stats": "스탯",
    "rules": "전투 공통 규칙",
    "gemstones": "젬스톤",
    "monsters": "몬스터",
    "skills": "스킬",
    "relics": "유물",
    "progression": "성장과 구매 설정",
    "categories": "강화 분류",
    "nodes": "강화 노드",
    "bossRewards": "보스 보상",
    "entities": "항목 이름과 콘셉트",
    "fieldHelp": "필드 도움말",
    "implementation": "구현 현황",
    "displayName": "표시 이름",
    "valueLabel": "화면 표시값",
    "key": "영문 필드 경로",
    "unit": "단위",
    "status": "구현 상태",
    "schemaVersion": "스냅샷 스키마 버전",
    "balanceVersion": "밸런스 버전",
    "attackPower": "공격력",
    "attackRadiusWorldUnits": "자동 공격 반경",
    "attackCooldownSeconds": "자동 공격 쿨타임",
    "criticalChancePercent": "치명타 확률",
    "bossDamageMultiplier": "보스 피해 배율",
    "normalFieldDurationSeconds": "일반 필드 제한 시간",
    "id": "고정 식별자",
    "enabled": "사용 가능 여부",
    "amount": "보유량",
    "productionCount": "1회 생산 마릿수",
    "hitPoints": "체력",
    "spawnIntervalSeconds": "생성 주기",
    "garnetReward": "처치 가넷 보상",
    "gemstoneId": "추가 젬 식별자",
    "gemstoneAmount": "추가 젬 수량",
    "gemstoneChancePercent": "추가 젬 확률",
    "relicFragmentId": "유물 조각 식별자",
    "relicFragmentChancePercent": "유물 조각 확률",
    "damage": "스킬 피해",
    "radiusWorldUnits": "스킬 반경",
    "cooldownSeconds": "스킬 쿨타임",
    "level": "유물 레벨",
    "fragments": "보유 유물 조각",
    "criticalDamageMultiplier": "치명타 피해 배율",
    "globalAliveLimit": "전체 생존 몬스터 상한",
    "perMonsterAliveLimit": "종별 생존 몬스터 상한",
    "bossFieldDurationSeconds": "보스 필드 제한 시간",
    "savedProgressPolicy": "저장 진행도 적용 방식",
    "initialBossTier": "초기 보스 단계",
    "relicAttackPercentPerLevel": "일반 유물 레벨당 공격력 증가",
    "relicBossDamagePercentPerLevel": "보스 유물 레벨당 보스 피해 증가",
    "scaleSkillDamageWithAttack": "공격력 성장에 따른 스킬 피해 비례 적용",
    "tab": "분류 탭",
    "cost": "구매 비용",
    "currencyId": "결제 재화",
    "requiredBossTier": "필요 보스 단계",
    "prerequisiteNodeId": "선행 노드",
    "startsUnlocked": "초기 구매 여부",
    "operation": "수치 적용 방식",
    "value": "효과 값",
    "tier": "보스 단계",
    "firstClearFragmentAmount": "첫 클리어 유물 조각"
}
EXPLANATIONS = {
    "behaviorType": "MonsterBehaviorType enum의 숫자 코드입니다. 현재 0=None(특성 없음)만 정의합니다. 지그재그·은신·무적 동작은 미구현이며, 추후 enum과 스키마를 함께 확장합니다.",
    "documentVersion": "전체 게임 데이터 문서 형식의 버전입니다. 전투 스냅샷 schemaVersion과 구분합니다.",
    "locale": "게임에서 읽는 데이터 원본은 영어(en)로 고정됩니다. 게임 화면의 표시 언어를 바꾸는 설정은 아닙니다.",
    "description": "해당 항목의 설명 문구입니다. 수치 계산에는 직접 사용하지 않습니다.",
    "schemaVersion": "전투 정보 구조의 버전입니다. 현재 허용 버전은 3입니다.",
    "balanceVersion": "수치 개편을 구분하는 버전입니다. 전투 시작 스냅샷에 함께 기록됩니다.",
    "attackPower": "기본 자동 공격 한 번의 피해입니다. 강화 효과를 적용하기 전 파일 기준값입니다. 정수로 입력합니다.",
    "attackRadiusWorldUnits": "자동 공격의 원형 반경입니다. 지름·픽셀·배율이 아닌 월드 단위입니다.",
    "attackCooldownSeconds": "기본 자동 공격 사이의 대기 시간입니다. 작을수록 자주 공격하며 0.05초 미만은 허용하지 않습니다.",
    "criticalChancePercent": "치명타가 발생할 확률입니다. 15는 15%이며 허용 범위는 0~100입니다.",
    "bossDamageMultiplier": "보스에게 주는 피해 배율입니다. 1은 기본 피해, 1.5는 150% 피해입니다.",
    "normalFieldDurationSeconds": "일반 필드 한 판의 기본 제한 시간입니다. 강화 후에도 최대 30초입니다.",
    "criticalDamageMultiplier": "치명타일 때 피해에 곱하는 배율입니다. 2는 두 배 피해입니다.",
    "globalAliveLimit": "모든 몬스터 종류를 합친 동시 생존 수의 상한입니다. 성능 예산상 최대 80입니다.",
    "perMonsterAliveLimit": "각 몬스터 종류별 동시 생존 수의 상한입니다. 전체 상한보다 클 수 없습니다.",
    "bossFieldDurationSeconds": "보스 필드 제한 시간입니다. 보스 전투 자체는 별도 미구현 항목이며 현재 기본 설정은 60초입니다.",
    "id": "코드·저장 데이터·다른 JSON 항목이 함께 사용하는 고정 식별자입니다. 표시 이름과 다르며 임의 변경 시 저장 이관이 필요합니다.",
    "enabled": "이 항목이 활성화되어 있는지 나타냅니다. true는 활성, false는 비활성입니다.",
    "amount": "보유한 젬 수량입니다. 0 이상의 Int64 정수이며 overlay 정책에서는 기존 저장 잔액을 적용합니다.",
    "productionCount": "해당 몬스터의 생성 주기가 돌아올 때 한 번에 생성할 마릿수입니다. 전체 누적 처치 수가 아닙니다.",
    "hitPoints": "몬스터 한 마리의 최대 체력입니다. 1 이상의 Int64 정수입니다.",
    "spawnIntervalSeconds": "해당 종류의 몬스터 생성 기회 사이의 간격입니다. 초 단위입니다.",
    "garnetReward": "몬스터 처치 또는 보스 승리 때 지급하는 기본 가넷 수량입니다. 추가 젬 보상과 별도로 지급합니다.",
    "gemstoneId": "추가 보상으로 지급할 젬의 고정 ID입니다.",
    "gemstoneAmount": "추가 젬 보상 판정에 성공했을 때 지급하는 수량입니다. 0이면 추가 지급하지 않습니다.",
    "gemstoneChancePercent": "몬스터 처치 시 추가 젬을 얻을 확률입니다. 100은 확정 지급, 0은 지급하지 않음입니다.",
    "relicFragmentId": "드롭하는 유물 조각의 재화 ID입니다. 유물 강화 비용의 currencyId와 연결됩니다.",
    "relicFragmentChancePercent": "해당 유물 조각을 얻을 확률입니다. 3은 3%입니다.",
    "damage": "스킬이 한 번 발동할 때의 기본 피해입니다. 강화와 공격력 성장 연동을 적용한 최종 피해가 전투에 전달됩니다.",
    "radiusWorldUnits": "스킬이 적용되는 원형 범위의 반경입니다. 월드 단위이며 현재 공통 실행기는 커서 중심입니다.",
    "cooldownSeconds": "해당 스킬 발동 사이의 대기 시간입니다. 기본 공격 쿨타임과 독립적입니다.",
    "level": "유물의 시작 레벨입니다. 0은 미획득이며 최대 5입니다. 레벨당 효과는 progression에서 정합니다.",
    "fragments": "이 유물의 보유 조각 수량입니다. 강화 구매 시 소모되며 overlay에서는 저장된 수량을 적용합니다.",
    "savedProgressPolicy": "overlay는 JSON 기본값 위에 기존 지갑·구매 기록을 적용합니다. fileOnly는 JSON 상태로 시작하며 기존 저장을 읽거나 쓰지 않습니다.",
    "initialBossTier": "시작 시 적용할 보스 진행 단계입니다. 0~5이며 노드의 requiredBossTier 조건에 사용합니다.",
    "relicAttackPercentPerLevel": "일반 유물 레벨 1개당 더해지는 공격력 증가율입니다. 2이면 전체 일반 유물 레벨 합계에 2%를 곱해 가산합니다.",
    "relicBossDamagePercentPerLevel": "보스 유물 레벨 1개당 더해지는 보스 피해 증가율입니다. 일반 유물의 공격력 효과와 구분합니다.",
    "scaleSkillDamageWithAttack": "true이면 스킬 피해가 파일의 기본 공격력 대비 성장한 공격력 비율에 따라 증가합니다. false이면 이 연동을 끕니다.",
    "cost": "이 노드를 구매할 때 한 번 소모하는 재화 수량입니다. 재화 종류는 currencyId에서 지정합니다.",
    "currencyId": "구매 비용을 지불할 재화 ID입니다. 젬 또는 특정 유물 조각을 가리킵니다.",
    "requiredBossTier": "이 노드를 구매하기 위해 필요한 최소 보스 단계입니다. 0이면 보스 조건이 없습니다.",
    "prerequisiteNodeId": "먼저 구매해야 하는 노드의 ID입니다. 빈 문자열이면 선행 노드 조건이 없습니다.",
    "startsUnlocked": "스탯 기본 노드 및 스킬 강화 노드의 시작 구매 설정입니다. 몬스터·스킬 해금·유물 시작 상태는 information 값을 우선합니다.",
    "operation": "효과 적용 방식입니다. baseline=기본값 사용, set=절대값 설정, add=기본값에 더하기, multiply=현재 값에 배율 곱하기, enable=활성화입니다.",
    "value": "노드 효과의 숫자입니다. set은 절대값, add는 기본값에 더할 값(쿨타임 감소는 음수), multiply는 배율입니다. baseline의 0은 피해 0이 아니라 기본값을 그대로 쓰는 표시입니다.",
    "tab": "노드가 속할 영역입니다. stats=스탯, skills=스킬, monsters=몬스터, relics=유물입니다.",
    "tier": "보스 보상 단계입니다. 1~5이며 boss.v1~boss.v5와 대응합니다.",
    "firstClearFragmentAmount": "해당 보스를 처음 클리어했을 때 지급하도록 정의된 유물 조각 수량입니다.",
    "prefabKey": "등록된 MonsterDefinition의 외형 키입니다. JSON만 수정해서 임의 경로의 프리팹을 로드하지는 않습니다.",
    "displayName": "사람에게 보여 주는 이름입니다. 연결용 고정 ID는 id를 사용합니다.",
    "valueLabel": "노드 UI에 표시할 짧은 문구입니다. 실제 계산은 operation과 value 또는 information의 숫자를 사용합니다.",
    "key": "이 도움말이 설명하는 영문 JSON 필드 경로입니다. []는 배열의 각 항목을 뜻합니다.",
    "unit": "값의 단위 또는 데이터 형식입니다. Int64는 64비트 정수, seconds는 초, world units는 월드 단위입니다.",
    "status": "실제 구현 상태입니다. 미구현 또는 공통 실행기만 있는 상태를 완성 기능과 구분합니다."
}
TRANSLATIONS = {
    "en": "영어 원본",
    "The sole runtime source for combat and progression. Edit gameplay values only in this English JSON. The Korean annotated reference lives under docs and is never loaded by the game. information is the baseline; progression contains every upgrade, cost and effect. overlay applies saved progress; fileOnly never reads or writes the player save. Data-file language does not select UI language.": "게임에서 사용하는 유일한 원본은 영어 JSON입니다. 한국어 해설은 docs 아래에만 있으며 게임에서 읽지 않습니다. information은 기본 상태, progression은 전체 강화·비용·효과입니다. overlay는 저장 적용, fileOnly는 저장 읽기/쓰기 없이 동작합니다. 원본 데이터 언어와 UI 언어는 별개입니다.",
    "Attack Power 1": "공격력 1",
    "Baseline is read from information.stats.attackPower.": "기본값은 information.stats.attackPower에서 읽습니다.",
    "JSON baseline": "JSON 기본값",
    "Attack Power 2": "공격력 2",
    "Set attackPower to 3.": "attackPower을 3로 설정합니다.",
    "Attack Power 3": "공격력 3",
    "Set attackPower to 6.": "attackPower을 6로 설정합니다.",
    "Attack Power 4": "공격력 4",
    "Set attackPower to 10.": "attackPower을 10로 설정합니다.",
    "Attack Power 5": "공격력 5",
    "Set attackPower to 16.": "attackPower을 16로 설정합니다.",
    "Attack Power 6": "공격력 6",
    "Set attackPower to 24.": "attackPower을 24로 설정합니다.",
    "Attack Power 7": "공격력 7",
    "Set attackPower to 35.": "attackPower을 35로 설정합니다.",
    "Attack Power 8": "공격력 8",
    "Set attackPower to 50.": "attackPower을 50로 설정합니다.",
    "Attack Power 9": "공격력 9",
    "Set attackPower to 70.": "attackPower을 70로 설정합니다.",
    "Attack Power 10": "공격력 10",
    "Set attackPower to 100.": "attackPower을 100로 설정합니다.",
    "Automatic Radius 1": "자동 반경 1",
    "Baseline is read from information.stats.attackRadiusWorldUnits.": "기본값은 information.stats.attackRadiusWorldUnits에서 읽습니다.",
    "Automatic Radius 2": "자동 반경 2",
    "Set attackRadiusWorldUnits to 1.897919u.": "attackRadiusWorldUnits을 1.897919u로 설정합니다.",
    "Automatic Radius 3": "자동 반경 3",
    "Set attackRadiusWorldUnits to 2.0704571u.": "attackRadiusWorldUnits을 2.0704571u로 설정합니다.",
    "Automatic Radius 4": "자동 반경 4",
    "Set attackRadiusWorldUnits to 2.2429952u.": "attackRadiusWorldUnits을 2.2429952u로 설정합니다.",
    "Automatic Radius 5": "자동 반경 5",
    "Set attackRadiusWorldUnits to 2.4155333u.": "attackRadiusWorldUnits을 2.4155333u로 설정합니다.",
    "Automatic Radius 6": "자동 반경 6",
    "Set attackRadiusWorldUnits to 2.5880713u.": "attackRadiusWorldUnits을 2.5880713u로 설정합니다.",
    "Automatic Radius 7": "자동 반경 7",
    "Set attackRadiusWorldUnits to 3.4507618u.": "attackRadiusWorldUnits을 3.4507618u로 설정합니다.",
    "Automatic Radius 8": "자동 반경 8",
    "Set attackRadiusWorldUnits to 5.1761427u.": "attackRadiusWorldUnits을 5.1761427u로 설정합니다.",
    "Automatic Radius 9": "자동 반경 9",
    "Set attackRadiusWorldUnits to 8.6269045u.": "attackRadiusWorldUnits을 8.6269045u로 설정합니다.",
    "Automatic Radius 10": "자동 반경 10",
    "Set attackRadiusWorldUnits to 13.8030472u.": "attackRadiusWorldUnits을 13.8030472u로 설정합니다.",
    "Automatic Radius 11": "자동 반경 11",
    "Set attackRadiusWorldUnits to 34.507618u.": "attackRadiusWorldUnits을 34.507618u로 설정합니다.",
    "Attack Cooldown 1": "공격 쿨타임 1",
    "Baseline is read from information.stats.attackCooldownSeconds.": "기본값은 information.stats.attackCooldownSeconds에서 읽습니다.",
    "Attack Cooldown 2": "공격 쿨타임 2",
    "Set attackCooldownSeconds to 0.65s.": "attackCooldownSeconds을 0.65s로 설정합니다.",
    "Attack Cooldown 3": "공격 쿨타임 3",
    "Set attackCooldownSeconds to 0.5s.": "attackCooldownSeconds을 0.5s로 설정합니다.",
    "Attack Cooldown 4": "공격 쿨타임 4",
    "Set attackCooldownSeconds to 0.35s.": "attackCooldownSeconds을 0.35s로 설정합니다.",
    "Attack Cooldown 5": "공격 쿨타임 5",
    "Set attackCooldownSeconds to 0.2s.": "attackCooldownSeconds을 0.2s로 설정합니다.",
    "Critical Chance 1": "치명타 1",
    "Baseline is read from information.stats.criticalChancePercent.": "기본값은 information.stats.criticalChancePercent에서 읽습니다.",
    "Critical Chance 2": "치명타 2",
    "Set criticalChancePercent to 5%.": "criticalChancePercent을 5%로 설정합니다.",
    "Critical Chance 3": "치명타 3",
    "Set criticalChancePercent to 10%.": "criticalChancePercent을 10%로 설정합니다.",
    "Critical Chance 4": "치명타 4",
    "Set criticalChancePercent to 20%.": "criticalChancePercent을 20%로 설정합니다.",
    "Critical Chance 5": "치명타 5",
    "Set criticalChancePercent to 30%.": "criticalChancePercent을 30%로 설정합니다.",
    "Critical Chance 6": "치명타 6",
    "Set criticalChancePercent to 50%.": "criticalChancePercent을 50%로 설정합니다.",
    "Critical Chance 7": "치명타 7",
    "Set criticalChancePercent to 75%.": "criticalChancePercent을 75%로 설정합니다.",
    "Critical Chance 8": "치명타 8",
    "Set criticalChancePercent to 100%.": "criticalChancePercent을 100%로 설정합니다.",
    "Normal Field Duration 1": "일반 필드 시간 1",
    "Baseline is read from information.stats.normalFieldDurationSeconds.": "기본값은 information.stats.normalFieldDurationSeconds에서 읽습니다.",
    "Normal Field Duration 2": "일반 필드 시간 2",
    "Set normalFieldDurationSeconds to 20s.": "normalFieldDurationSeconds을 20s로 설정합니다.",
    "Normal Field Duration 3": "일반 필드 시간 3",
    "Set normalFieldDurationSeconds to 25s.": "normalFieldDurationSeconds을 25s로 설정합니다.",
    "Normal Field Duration 4": "일반 필드 시간 4",
    "Set normalFieldDurationSeconds to 30s.": "normalFieldDurationSeconds을 30s로 설정합니다.",
    "Boss Damage 1": "보스 피해 1",
    "Set bossDamageMultiplier to 1.25x.": "bossDamageMultiplier을 1.25x로 설정합니다.",
    "Boss Damage 2": "보스 피해 2",
    "Set bossDamageMultiplier to 1.6x.": "bossDamageMultiplier을 1.6x로 설정합니다.",
    "Boss Damage 3": "보스 피해 3",
    "Set bossDamageMultiplier to 2.1x.": "bossDamageMultiplier을 2.1x로 설정합니다.",
    "Boss Damage 4": "보스 피해 4",
    "Set bossDamageMultiplier to 2.8x.": "bossDamageMultiplier을 2.8x로 설정합니다.",
    "Boss Damage 5": "보스 피해 5",
    "Set bossDamageMultiplier to 4x.": "bossDamageMultiplier을 4x로 설정합니다.",
    "Fireball": "파이어볼",
    "Enable the skill. Initial availability is read from information.skills.": "스킬을 사용할 수 있게 합니다. 초기 여부는 information.skills에서 읽습니다.",
    "Unlock skill": "스킬 해금",
    "Damage Upgrade": "피해량 강화",
    "Multiply Fireball damage by 1.35.": "파이어볼의 damage 값에 1.35를 곱합니다.",
    "Radius Upgrade": "범위 강화",
    "Multiply Fireball radius by 1.3.": "파이어볼의 radius 값에 1.3를 곱합니다.",
    "Cooldown Upgrade": "쿨타임 강화",
    "Multiply Fireball cooldown by 0.8.": "파이어볼의 cooldown 값에 0.8를 곱합니다.",
    "Lightning Bolt": "라이트닝 볼트",
    "Multiply Lightning Bolt damage by 1.35.": "라이트닝 볼트의 damage 값에 1.35를 곱합니다.",
    "Multiply Lightning Bolt radius by 1.3.": "라이트닝 볼트의 radius 값에 1.3를 곱합니다.",
    "Multiply Lightning Bolt cooldown by 0.8.": "라이트닝 볼트의 cooldown 값에 0.8를 곱합니다.",
    "Freezing": "프리즈닝",
    "Multiply Freezing damage by 1.35.": "프리즈닝의 damage 값에 1.35를 곱합니다.",
    "Multiply Freezing radius by 1.3.": "프리즈닝의 radius 값에 1.3를 곱합니다.",
    "Multiply Freezing cooldown by 0.8.": "프리즈닝의 cooldown 값에 0.8를 곱합니다.",
    "Hurricane": "허리케인",
    "Multiply Hurricane damage by 1.35.": "허리케인의 damage 값에 1.35를 곱합니다.",
    "Multiply Hurricane radius by 1.3.": "허리케인의 radius 값에 1.3를 곱합니다.",
    "Multiply Hurricane cooldown by 0.8.": "허리케인의 cooldown 값에 0.8를 곱합니다.",
    "Meteor": "메테오",
    "Multiply Meteor damage by 1.35.": "메테오의 damage 값에 1.35를 곱합니다.",
    "Multiply Meteor radius by 1.3.": "메테오의 radius 값에 1.3를 곱합니다.",
    "Multiply Meteor cooldown by 0.8.": "메테오의 cooldown 값에 0.8를 곱합니다.",
    "Dragon Breath": "드래곤 브레스",
    "Multiply Dragon Breath damage by 1.35.": "드래곤 브레스의 damage 값에 1.35를 곱합니다.",
    "Multiply Dragon Breath radius by 1.3.": "드래곤 브레스의 radius 값에 1.3를 곱합니다.",
    "Multiply Dragon Breath cooldown by 0.8.": "드래곤 브레스의 cooldown 값에 0.8를 곱합니다.",
    "Cursor Aura": "커서 오라",
    "Multiply Cursor Aura damage by 1.35.": "커서 오라의 damage 값에 1.35를 곱합니다.",
    "Multiply Cursor Aura radius by 1.3.": "커서 오라의 radius 값에 1.3를 곱합니다.",
    "Multiply Cursor Aura cooldown by 0.8.": "커서 오라의 cooldown 값에 0.8를 곱합니다.",
    "Garnet Stump": "가넷 그루터기",
    "Guardian of garnet crystals left in the forest. Supplies Garnet on defeat.": "숲에 남은 가넷 결정의 수호자. 처치 시 가넷 공급.",
    "Enable monster": "몬스터 등장",
    "Production 2": "생산량 2",
    "Spawn 2 monsters per spawn opportunity.": "한 번의 생성 기회에 2마리 생성.",
    "Production 3": "생산량 3",
    "Spawn 3 monsters per spawn opportunity.": "한 번의 생성 기회에 3마리 생성.",
    "Production 4": "생산량 4",
    "Spawn 4 monsters per spawn opportunity.": "한 번의 생성 기회에 4마리 생성.",
    "Topaz Cave Bat": "토파즈 동굴박쥐",
    "Cave collector carrying topaz. Supplies Topaz on defeat.": "토파즈를 품은 동굴의 수집가. 처치 시 토파즈 공급.",
    "Amber Mushroom": "호박 버섯",
    "Golden spore creature growing topaz. Supplies Topaz on defeat.": "토파즈가 자라난 황금 포자 생물. 처치 시 토파즈 공급.",
    "Amethyst Mask Ghost": "자수정 가면유령",
    "A lingering spirit bound to an amethyst mask. Supplies Amethyst on defeat.": "자수정 가면에 깃든 잔령. 처치 시 자수정 공급.",
    "Crystal Scorpion": "수정 전갈",
    "Vein sentinel wearing an amethyst shell. Supplies Amethyst on defeat.": "자수정 껍질을 두른 광맥 파수꾼. 처치 시 자수정 공급.",
    "Sapphire Snow Fairy": "사파이어 눈요정",
    "Spirit of sapphire frost. Supplies Sapphire on defeat.": "사파이어 서리의 정령. 처치 시 사파이어 공급.",
    "Frozen Spider": "빙결 거미",
    "Spider guarding sapphire cocoons. Supplies Sapphire on defeat.": "사파이어 고치를 지키는 거미. 처치 시 사파이어 공급.",
    "Diamond Iron Golem": "다이아 철골렘",
    "Iron giant with a diamond core. Supplies Diamond on defeat.": "다이아 핵을 품은 철의 거인. 처치 시 다이아몬드 공급.",
    "Dragon Ember Bud": "드래곤 불꽃봉오리",
    "Bud blooming in the heat of dragon gems. Supplies Dragon Gem on defeat.": "드래곤 젬의 열기로 피어난 봉오리. 처치 시 드래곤 젬 공급.",
    "Ancient Skeleton Lord": "고대 해골군주",
    "Ancient lord revived by dragon gems. Supplies Dragon Gem on defeat.": "드래곤 젬으로 되살아난 고대 군주. 처치 시 드래곤 젬 공급.",
    "Heart of the Forest 1": "숲의 심장 1",
    "Upgrade relic to level 1.": "유물 레벨을 1로 강화합니다.",
    "Level 1": "레벨 1",
    "Heart of the Forest 2": "숲의 심장 2",
    "Upgrade relic to level 2.": "유물 레벨을 2로 강화합니다.",
    "Level 2": "레벨 2",
    "Heart of the Forest 3": "숲의 심장 3",
    "Upgrade relic to level 3.": "유물 레벨을 3로 강화합니다.",
    "Level 3": "레벨 3",
    "Heart of the Forest 4": "숲의 심장 4",
    "Upgrade relic to level 4.": "유물 레벨을 4로 강화합니다.",
    "Level 4": "레벨 4",
    "Heart of the Forest 5": "숲의 심장 5",
    "Upgrade relic to level 5.": "유물 레벨을 5로 강화합니다.",
    "Level 5": "레벨 5",
    "Cave Fang 1": "동굴의 송곳니 1",
    "Cave Fang 2": "동굴의 송곳니 2",
    "Cave Fang 3": "동굴의 송곳니 3",
    "Cave Fang 4": "동굴의 송곳니 4",
    "Cave Fang 5": "동굴의 송곳니 5",
    "Golden Spore 1": "황금 포자 1",
    "Golden Spore 2": "황금 포자 2",
    "Golden Spore 3": "황금 포자 3",
    "Golden Spore 4": "황금 포자 4",
    "Golden Spore 5": "황금 포자 5",
    "Lingering Mask 1": "잔령의 가면 1",
    "Lingering Mask 2": "잔령의 가면 2",
    "Lingering Mask 3": "잔령의 가면 3",
    "Lingering Mask 4": "잔령의 가면 4",
    "Lingering Mask 5": "잔령의 가면 5",
    "Crystal Stinger 1": "수정 독침 1",
    "Crystal Stinger 2": "수정 독침 2",
    "Crystal Stinger 3": "수정 독침 3",
    "Crystal Stinger 4": "수정 독침 4",
    "Crystal Stinger 5": "수정 독침 5",
    "Frost Crystal 1": "서리 결정 1",
    "Frost Crystal 2": "서리 결정 2",
    "Frost Crystal 3": "서리 결정 3",
    "Frost Crystal 4": "서리 결정 4",
    "Frost Crystal 5": "서리 결정 5",
    "Frozen Thread 1": "빙결 실타래 1",
    "Frozen Thread 2": "빙결 실타래 2",
    "Frozen Thread 3": "빙결 실타래 3",
    "Frozen Thread 4": "빙결 실타래 4",
    "Frozen Thread 5": "빙결 실타래 5",
    "Undying Core 1": "불멸의 핵 1",
    "Undying Core 2": "불멸의 핵 2",
    "Undying Core 3": "불멸의 핵 3",
    "Undying Core 4": "불멸의 핵 4",
    "Undying Core 5": "불멸의 핵 5",
    "Dragon Ember 1": "용의 불씨 1",
    "Dragon Ember 2": "용의 불씨 2",
    "Dragon Ember 3": "용의 불씨 3",
    "Dragon Ember 4": "용의 불씨 4",
    "Dragon Ember 5": "용의 불씨 5",
    "Ancient Crown 1": "고대 왕관 1",
    "Ancient Crown 2": "고대 왕관 2",
    "Ancient Crown 3": "고대 왕관 3",
    "Ancient Crown 4": "고대 왕관 4",
    "Ancient Crown 5": "고대 왕관 5",
    "Boss Relic 1 1": "보스 유물 1 1",
    "Boss Relic 1 2": "보스 유물 1 2",
    "Boss Relic 1 3": "보스 유물 1 3",
    "Boss Relic 1 4": "보스 유물 1 4",
    "Boss Relic 1 5": "보스 유물 1 5",
    "Boss Relic 2 1": "보스 유물 2 1",
    "Boss Relic 2 2": "보스 유물 2 2",
    "Boss Relic 2 3": "보스 유물 2 3",
    "Boss Relic 2 4": "보스 유물 2 4",
    "Boss Relic 2 5": "보스 유물 2 5",
    "Boss Relic 3 1": "보스 유물 3 1",
    "Boss Relic 3 2": "보스 유물 3 2",
    "Boss Relic 3 3": "보스 유물 3 3",
    "Boss Relic 3 4": "보스 유물 3 4",
    "Boss Relic 3 5": "보스 유물 3 5",
    "Boss Relic 4 1": "보스 유물 4 1",
    "Boss Relic 4 2": "보스 유물 4 2",
    "Boss Relic 4 3": "보스 유물 4 3",
    "Boss Relic 4 4": "보스 유물 4 4",
    "Boss Relic 4 5": "보스 유물 4 5",
    "Boss Relic 5 1": "보스 유물 5 1",
    "Boss Relic 5 2": "보스 유물 5 2",
    "Boss Relic 5 3": "보스 유물 5 3",
    "Boss Relic 5 4": "보스 유물 5 4",
    "Boss Relic 5 5": "보스 유물 5 5",
    "Attack Power": "공격력",
    "Combat value: attackPower.": "전투 정보의 attackPower 값입니다.",
    "Automatic Radius": "자동 반경",
    "Combat value: attackRadiusWorldUnits.": "전투 정보의 attackRadiusWorldUnits 값입니다.",
    "Attack Cooldown": "공격 쿨타임",
    "Combat value: attackCooldownSeconds.": "전투 정보의 attackCooldownSeconds 값입니다.",
    "Critical Chance": "치명타",
    "Combat value: criticalChancePercent.": "전투 정보의 criticalChancePercent 값입니다.",
    "Normal Field Duration": "일반 필드 시간",
    "Combat value: normalFieldDurationSeconds.": "전투 정보의 normalFieldDurationSeconds 값입니다.",
    "Boss Damage": "보스 피해",
    "Combat value: bossDamageMultiplier.": "전투 정보의 bossDamageMultiplier 값입니다.",
    "Garnet": "가넷",
    "Reward from ordinary monsters, with no separate gemstone unlock. enabled indicates an available source; amount is the wallet balance.": "일반 몬스터 처치 보상. 별도 젬 해금 없음. enabled는 공급원 여부, amount는 보유량입니다.",
    "Topaz": "토파즈",
    "Amethyst": "자수정",
    "Sapphire": "사파이어",
    "Diamond": "다이아몬드",
    "Dragon Gem": "드래곤 젬",
    "Current implementation: cooldown-based circular damage at the cursor. Unique projectiles, status effects and visuals are not implemented.": "현재 구현: 쿨타임마다 커서 중심 원형 피해. 고유 투사체·상태 이상·연출은 별도 미구현.",
    "Guardian of garnet crystals left in the forest": "숲에 남은 가넷 결정의 수호자",
    "Cave collector carrying topaz": "토파즈를 품은 동굴의 수집가",
    "Golden spore creature growing topaz": "토파즈가 자라난 황금 포자 생물",
    "A lingering spirit bound to an amethyst mask": "자수정 가면에 깃든 잔령",
    "Vein sentinel wearing an amethyst shell": "자수정 껍질을 두른 광맥 파수꾼",
    "Spirit of sapphire frost": "사파이어 서리의 정령",
    "Spider guarding sapphire cocoons": "사파이어 고치를 지키는 거미",
    "Iron giant with a diamond core": "다이아 핵을 품은 철의 거인",
    "Bud blooming in the heat of dragon gems": "드래곤 젬의 열기로 피어난 봉오리",
    "Ancient lord revived by dragon gems": "드래곤 젬으로 되살아난 고대 군주",
    "Heart of the Forest": "숲의 심장",
    "Each level increases attack power. Effect percentages come from progression.": "레벨당 공격력 증가. 효과 수치는 progression의 유물 퍼센트를 사용합니다.",
    "Cave Fang": "동굴의 송곳니",
    "Golden Spore": "황금 포자",
    "Lingering Mask": "잔령의 가면",
    "Crystal Stinger": "수정 독침",
    "Frost Crystal": "서리 결정",
    "Frozen Thread": "빙결 실타래",
    "Undying Core": "불멸의 핵",
    "Dragon Ember": "용의 불씨",
    "Ancient Crown": "고대 왕관",
    "Boss Relic 1": "보스 유물 1",
    "Each level increases boss damage. Effect percentages come from progression.": "레벨당 보스 피해 증가. 효과 수치는 progression의 유물 퍼센트를 사용합니다.",
    "Boss Relic 2": "보스 유물 2",
    "Boss Relic 3": "보스 유물 3",
    "Boss Relic 4": "보스 유물 4",
    "Boss Relic 5": "보스 유물 5",
    "Boss 1": "보스 1",
    "Reward data only. Dedicated boss combat, patterns, HP and visual bindings are not implemented; no invented values are provided.": "보상 데이터만 확정. 전용 보스 전투·패턴·HP·외형 연결은 미구현이며 임의 수치를 넣지 않습니다.",
    "Boss 2": "보스 2",
    "Boss 3": "보스 3",
    "Boss 4": "보스 4",
    "Boss 5": "보스 5",
    "Snapshot schema version": "스냅샷 스키마 버전",
    "This key maps to the actual JSON field information.schemaVersion.": "이 키는 실제 JSON 필드 information.schemaVersion에 대응합니다.",
    "Balance version": "밸런스 버전",
    "This key maps to the actual JSON field information.balanceVersion.": "이 키는 실제 JSON 필드 information.balanceVersion에 대응합니다.",
    "Attack power": "공격력",
    "This key maps to the actual JSON field information.stats.attackPower.": "이 키는 실제 JSON 필드 information.stats.attackPower에 대응합니다.",
    "Automatic attack radius": "자동 공격 반경",
    "This key maps to the actual JSON field information.stats.attackRadiusWorldUnits.": "이 키는 실제 JSON 필드 information.stats.attackRadiusWorldUnits에 대응합니다.",
    "Automatic attack cooldown": "자동 공격 쿨타임",
    "This key maps to the actual JSON field information.stats.attackCooldownSeconds.": "이 키는 실제 JSON 필드 information.stats.attackCooldownSeconds에 대응합니다.",
    "Critical chance": "치명타 확률",
    "This key maps to the actual JSON field information.stats.criticalChancePercent.": "이 키는 실제 JSON 필드 information.stats.criticalChancePercent에 대응합니다.",
    "Boss damage multiplier": "보스 피해 배율",
    "This key maps to the actual JSON field information.stats.bossDamageMultiplier.": "이 키는 실제 JSON 필드 information.stats.bossDamageMultiplier에 대응합니다.",
    "Normal field duration": "일반 필드 제한 시간",
    "This key maps to the actual JSON field information.stats.normalFieldDurationSeconds.": "이 키는 실제 JSON 필드 information.stats.normalFieldDurationSeconds에 대응합니다.",
    "Stable identifier": "고정 식별자",
    "This key maps to the actual JSON field information.gemstones[].id.": "이 키는 실제 JSON 필드 information.gemstones[].id에 대응합니다.",
    "Availability": "사용 가능 여부",
    "This key maps to the actual JSON field information.gemstones[].enabled.": "이 키는 실제 JSON 필드 information.gemstones[].enabled에 대응합니다.",
    "Wallet amount": "보유량",
    "This key maps to the actual JSON field information.gemstones[].amount.": "이 키는 실제 JSON 필드 information.gemstones[].amount에 대응합니다.",
    "This key maps to the actual JSON field information.monsters[].id.": "이 키는 실제 JSON 필드 information.monsters[].id에 대응합니다.",
    "This key maps to the actual JSON field information.monsters[].enabled.": "이 키는 실제 JSON 필드 information.monsters[].enabled에 대응합니다.",
    "Monsters per spawn opportunity": "1회 생산 마릿수",
    "This key maps to the actual JSON field information.monsters[].productionCount.": "이 키는 실제 JSON 필드 information.monsters[].productionCount에 대응합니다.",
    "Hit points": "체력",
    "This key maps to the actual JSON field information.monsters[].hitPoints.": "이 키는 실제 JSON 필드 information.monsters[].hitPoints에 대응합니다.",
    "Spawn interval": "생성 주기",
    "This key maps to the actual JSON field information.monsters[].spawnIntervalSeconds.": "이 키는 실제 JSON 필드 information.monsters[].spawnIntervalSeconds에 대응합니다.",
    "Garnet reward per kill": "처치 가넷 보상",
    "This key maps to the actual JSON field information.monsters[].garnetReward.": "이 키는 실제 JSON 필드 information.monsters[].garnetReward에 대응합니다.",
    "Bonus gemstone ID": "추가 젬 식별자",
    "This key maps to the actual JSON field information.monsters[].gemstoneId.": "이 키는 실제 JSON 필드 information.monsters[].gemstoneId에 대응합니다.",
    "Bonus gemstone amount": "추가 젬 수량",
    "This key maps to the actual JSON field information.monsters[].gemstoneAmount.": "이 키는 실제 JSON 필드 information.monsters[].gemstoneAmount에 대응합니다.",
    "Bonus gemstone chance": "추가 젬 확률",
    "This key maps to the actual JSON field information.monsters[].gemstoneChancePercent.": "이 키는 실제 JSON 필드 information.monsters[].gemstoneChancePercent에 대응합니다.",
    "Relic fragment ID": "유물 조각 식별자",
    "This key maps to the actual JSON field information.monsters[].relicFragmentId.": "이 키는 실제 JSON 필드 information.monsters[].relicFragmentId에 대응합니다.",
    "Relic fragment chance": "유물 조각 확률",
    "This key maps to the actual JSON field information.monsters[].relicFragmentChancePercent.": "이 키는 실제 JSON 필드 information.monsters[].relicFragmentChancePercent에 대응합니다.",
    "This key maps to the actual JSON field information.skills[].id.": "이 키는 실제 JSON 필드 information.skills[].id에 대응합니다.",
    "This key maps to the actual JSON field information.skills[].enabled.": "이 키는 실제 JSON 필드 information.skills[].enabled에 대응합니다.",
    "Skill damage": "스킬 피해",
    "This key maps to the actual JSON field information.skills[].damage.": "이 키는 실제 JSON 필드 information.skills[].damage에 대응합니다.",
    "Skill radius": "스킬 반경",
    "This key maps to the actual JSON field information.skills[].radiusWorldUnits.": "이 키는 실제 JSON 필드 information.skills[].radiusWorldUnits에 대응합니다.",
    "Skill cooldown": "스킬 쿨타임",
    "This key maps to the actual JSON field information.skills[].cooldownSeconds.": "이 키는 실제 JSON 필드 information.skills[].cooldownSeconds에 대응합니다.",
    "This key maps to the actual JSON field information.relics[].id.": "이 키는 실제 JSON 필드 information.relics[].id에 대응합니다.",
    "This key maps to the actual JSON field information.relics[].enabled.": "이 키는 실제 JSON 필드 information.relics[].enabled에 대응합니다.",
    "Relic level": "유물 레벨",
    "This key maps to the actual JSON field information.relics[].level.": "이 키는 실제 JSON 필드 information.relics[].level에 대응합니다.",
    "Owned relic fragments": "보유 유물 조각",
    "This key maps to the actual JSON field information.relics[].fragments.": "이 키는 실제 JSON 필드 information.relics[].fragments에 대응합니다.",
    "Critical damage multiplier": "치명타 피해 배율",
    "This key maps to the actual JSON field information.rules.criticalDamageMultiplier.": "이 키는 실제 JSON 필드 information.rules.criticalDamageMultiplier에 대응합니다.",
    "Global alive monster limit": "전체 생존 몬스터 상한",
    "This key maps to the actual JSON field information.rules.globalAliveLimit.": "이 키는 실제 JSON 필드 information.rules.globalAliveLimit에 대응합니다.",
    "Alive limit per species": "종별 생존 몬스터 상한",
    "This key maps to the actual JSON field information.rules.perMonsterAliveLimit.": "이 키는 실제 JSON 필드 information.rules.perMonsterAliveLimit에 대응합니다.",
    "Boss field duration": "보스 필드 제한 시간",
    "This key maps to the actual JSON field information.rules.bossFieldDurationSeconds.": "이 키는 실제 JSON 필드 information.rules.bossFieldDurationSeconds에 대응합니다.",
    "Saved progress policy": "저장 진행도 적용 방식",
    "This key maps to the actual JSON field progression.savedProgressPolicy.": "이 키는 실제 JSON 필드 progression.savedProgressPolicy에 대응합니다.",
    "Initial boss tier": "초기 보스 단계",
    "This key maps to the actual JSON field progression.initialBossTier.": "이 키는 실제 JSON 필드 progression.initialBossTier에 대응합니다.",
    "Attack increase per normal relic level": "일반 유물 레벨당 공격력 증가",
    "This key maps to the actual JSON field progression.relicAttackPercentPerLevel.": "이 키는 실제 JSON 필드 progression.relicAttackPercentPerLevel에 대응합니다.",
    "Boss damage increase per boss relic level": "보스 유물 레벨당 보스 피해 증가",
    "This key maps to the actual JSON field progression.relicBossDamagePercentPerLevel.": "이 키는 실제 JSON 필드 progression.relicBossDamagePercentPerLevel에 대응합니다.",
    "Scale skill damage with attack growth": "공격력 성장에 따른 스킬 피해 비례 적용",
    "This key maps to the actual JSON field progression.scaleSkillDamageWithAttack.": "이 키는 실제 JSON 필드 progression.scaleSkillDamageWithAttack에 대응합니다.",
    "This key maps to the actual JSON field progression.categories[].id.": "이 키는 실제 JSON 필드 progression.categories[].id에 대응합니다.",
    "Category tab": "분류 탭",
    "This key maps to the actual JSON field progression.categories[].tab.": "이 키는 실제 JSON 필드 progression.categories[].tab에 대응합니다.",
    "This key maps to the actual JSON field progression.categories[].nodes[].id.": "이 키는 실제 JSON 필드 progression.categories[].nodes[].id에 대응합니다.",
    "This key maps to the actual JSON field progression.categories[].nodes[].displayName.": "이 키는 실제 JSON 필드 progression.categories[].nodes[].displayName에 대응합니다.",
    "This key maps to the actual JSON field progression.categories[].nodes[].description.": "이 키는 실제 JSON 필드 progression.categories[].nodes[].description에 대응합니다.",
    "This key maps to the actual JSON field progression.categories[].nodes[].valueLabel.": "이 키는 실제 JSON 필드 progression.categories[].nodes[].valueLabel에 대응합니다.",
    "Purchase cost": "구매 비용",
    "This key maps to the actual JSON field progression.categories[].nodes[].cost.": "이 키는 실제 JSON 필드 progression.categories[].nodes[].cost에 대응합니다.",
    "Cost currency": "결제 재화",
    "This key maps to the actual JSON field progression.categories[].nodes[].currencyId.": "이 키는 실제 JSON 필드 progression.categories[].nodes[].currencyId에 대응합니다.",
    "Required boss tier": "필요 보스 단계",
    "This key maps to the actual JSON field progression.categories[].nodes[].requiredBossTier.": "이 키는 실제 JSON 필드 progression.categories[].nodes[].requiredBossTier에 대응합니다.",
    "Prerequisite node": "선행 노드",
    "This key maps to the actual JSON field progression.categories[].nodes[].prerequisiteNodeId.": "이 키는 실제 JSON 필드 progression.categories[].nodes[].prerequisiteNodeId에 대응합니다.",
    "Initially purchased": "초기 구매 여부",
    "This key maps to the actual JSON field progression.categories[].nodes[].startsUnlocked.": "이 키는 실제 JSON 필드 progression.categories[].nodes[].startsUnlocked에 대응합니다.",
    "Effect operation": "수치 적용 방식",
    "This key maps to the actual JSON field progression.categories[].nodes[].operation.": "이 키는 실제 JSON 필드 progression.categories[].nodes[].operation에 대응합니다.",
    "Effect value": "효과 값",
    "This key maps to the actual JSON field progression.categories[].nodes[].value.": "이 키는 실제 JSON 필드 progression.categories[].nodes[].value에 대응합니다.",
    "This key maps to the actual JSON field progression.bossRewards[].id.": "이 키는 실제 JSON 필드 progression.bossRewards[].id에 대응합니다.",
    "Boss tier": "보스 단계",
    "This key maps to the actual JSON field progression.bossRewards[].tier.": "이 키는 실제 JSON 필드 progression.bossRewards[].tier에 대응합니다.",
    "This key maps to the actual JSON field progression.bossRewards[].garnetReward.": "이 키는 실제 JSON 필드 progression.bossRewards[].garnetReward에 대응합니다.",
    "This key maps to the actual JSON field progression.bossRewards[].gemstoneId.": "이 키는 실제 JSON 필드 progression.bossRewards[].gemstoneId에 대응합니다.",
    "This key maps to the actual JSON field progression.bossRewards[].gemstoneAmount.": "이 키는 실제 JSON 필드 progression.bossRewards[].gemstoneAmount에 대응합니다.",
    "This key maps to the actual JSON field progression.bossRewards[].relicFragmentId.": "이 키는 실제 JSON 필드 progression.bossRewards[].relicFragmentId에 대응합니다.",
    "This key maps to the actual JSON field progression.bossRewards[].relicFragmentChancePercent.": "이 키는 실제 JSON 필드 progression.bossRewards[].relicFragmentChancePercent에 대응합니다.",
    "First-clear relic fragments": "첫 클리어 유물 조각",
    "This key maps to the actual JSON field progression.bossRewards[].firstClearFragmentAmount.": "이 키는 실제 JSON 필드 progression.bossRewards[].firstClearFragmentAmount에 대응합니다.",
    "Automatic single radius hits, cooldown, critical hits, per-species spawning and rewards. Normal fields capped at 30 seconds. UI blocks attacks; inspection and focus loss pause the clock.": "자동 반경 단일 타격, 쿨타임, 치명타, 종별 스폰과 보상. 일반 필드 최대 30초. UI 위 공격 금지, 팝업·포커스 상실 시 시계 일시정지.",
    "All 7 skills pass final damage, radius and cooldown to the shared radial executor. Projectiles, freezing, multi-ticks and directional breath remain unimplemented.": "7종 모두 최종 피해·반경·쿨타임을 공통 원형 판정기에 전달. 투사체·빙결·다중 틱·방향성 브레스는 아직 없음.",
    "Includes all five reward tiers. Dedicated encounters, patterns, parry and boss HP are not implemented and no values are fabricated.": "5단계 보상 정의는 포함. 전용 전투 진입·패턴·패링·보스 HP는 구현되지 않아 수치를 날조하지 않음.",
    "overlay applies saved wallets and purchases. fileOnly never reads/writes the existing save. File changes apply on next initialization. Combat results never overwrite these authored documents.": "overlay: 기존 지갑·구매 기록 적용. fileOnly: 기존 저장 읽기/쓰기 없음. 파일 변경은 다음 초기화에 반영. 파일 내용 자체를 전투 결과로 덮어쓰지 않음.",
    "No gameplay execution or Unity compilation. Static checks cover JSON, locale equivalence, node references and C# syntax.": "게임 실행 및 Unity 컴파일은 수행하지 않음. JSON, 두 언어 동등성, 노드 참조 및 C# 구문 정적 검사.",
    "overlay": "기존 저장 진행도 적용",
    "fileOnly": "JSON 기본값만 사용·기존 저장 읽기/쓰기 없음",
    "baseline": "파일 기본값 유지",
    "set": "절대값으로 설정",
    "multiply": "배율 곱하기",
    "enable": "활성화",
    "stats": "스탯",
    "skills": "스킬",
    "monsters": "몬스터",
    "relics": "유물",
    "implemented": "구현됨",
    "sharedRadialDamage": "공통 원형 피해 실행기만 구현",
    "notImplemented": "미구현",
    "playerPrefsPrototype": "PlayerPrefs 기반 임시 저장 구조",
    "staticOnly": "정적 검사만 수행",
    "seconds": "초",
    "percent": "퍼센트(%)",
    "multiplier": "배율",
    "count": "개수",
    "world units": "월드 단위",
    "boolean": "참/거짓",
    "asset key": "에셋 참조 키",
    "version": "버전",
    "number": "숫자",
    "string": "문자열",
    "ID": "고정 식별자",
    "Int64": "64비트 정수",
    "Int32": "32비트 정수",
    "level": "레벨",
    "tier": "단계",
    "stat.attack": "공격력",
    "stat.radius": "자동 반경",
    "stat.cooldown": "공격 쿨타임",
    "stat.critical": "치명타",
    "stat.fieldDuration": "일반 필드 시간",
    "stat.boss": "보스 피해",
    "gem.garnet": "가넷",
    "gem.topaz": "토파즈",
    "gem.amethyst": "자수정",
    "gem.sapphire": "사파이어",
    "gem.diamond": "다이아몬드",
    "gem.dragon": "드래곤 젬",
    "skill.fireball": "파이어볼",
    "skill.lightning": "라이트닝 볼트",
    "skill.freeze": "프리즈닝",
    "skill.hurricane": "허리케인",
    "skill.meteor": "메테오",
    "skill.dragonBreath": "드래곤 브레스",
    "skill.cursorAura": "커서 오라",
    "monster.01": "가넷 그루터기",
    "monster.02": "토파즈 동굴박쥐",
    "monster.03": "호박 버섯",
    "monster.04": "자수정 가면유령",
    "monster.05": "수정 전갈",
    "monster.06": "사파이어 눈요정",
    "monster.07": "빙결 거미",
    "monster.08": "다이아 철골렘",
    "monster.09": "드래곤 불꽃봉오리",
    "monster.10": "고대 해골군주",
    "relic.monster.01": "숲의 심장 1",
    "relic.monster.02": "동굴의 송곳니 1",
    "relic.monster.03": "황금 포자 1",
    "relic.monster.04": "잔령의 가면 1",
    "relic.monster.05": "수정 독침 1",
    "relic.monster.06": "서리 결정 1",
    "relic.monster.07": "빙결 실타래 1",
    "relic.monster.08": "불멸의 핵 1",
    "relic.monster.09": "용의 불씨 1",
    "relic.monster.10": "고대 왕관 1",
    "relic.boss.01": "보스 유물 1 1",
    "relic.boss.02": "보스 유물 2 1",
    "relic.boss.03": "보스 유물 3 1",
    "relic.boss.04": "보스 유물 4 1",
    "relic.boss.05": "보스 유물 5 1",
    "boss.v1": "보스 1",
    "boss.v2": "보스 2",
    "boss.v3": "보스 3",
    "boss.v4": "보스 4",
    "boss.v5": "보스 5",
    "stat.attack.01": "공격력 1",
    "stat.attack.02": "공격력 2",
    "stat.attack.03": "공격력 3",
    "stat.attack.04": "공격력 4",
    "stat.attack.05": "공격력 5",
    "stat.attack.06": "공격력 6",
    "stat.attack.07": "공격력 7",
    "stat.attack.08": "공격력 8",
    "stat.attack.09": "공격력 9",
    "stat.attack.10": "공격력 10",
    "stat.radius.01": "자동 반경 1",
    "stat.radius.02": "자동 반경 2",
    "stat.radius.03": "자동 반경 3",
    "stat.radius.04": "자동 반경 4",
    "stat.radius.05": "자동 반경 5",
    "stat.radius.06": "자동 반경 6",
    "stat.radius.07": "자동 반경 7",
    "stat.radius.08": "자동 반경 8",
    "stat.radius.09": "자동 반경 9",
    "stat.radius.10": "자동 반경 10",
    "stat.radius.11": "자동 반경 11",
    "stat.cooldown.01": "공격 쿨타임 1",
    "stat.cooldown.02": "공격 쿨타임 2",
    "stat.cooldown.03": "공격 쿨타임 3",
    "stat.cooldown.04": "공격 쿨타임 4",
    "stat.cooldown.05": "공격 쿨타임 5",
    "stat.critical.01": "치명타 1",
    "stat.critical.02": "치명타 2",
    "stat.critical.03": "치명타 3",
    "stat.critical.04": "치명타 4",
    "stat.critical.05": "치명타 5",
    "stat.critical.06": "치명타 6",
    "stat.critical.07": "치명타 7",
    "stat.critical.08": "치명타 8",
    "stat.fieldDuration.01": "일반 필드 시간 1",
    "stat.fieldDuration.02": "일반 필드 시간 2",
    "stat.fieldDuration.03": "일반 필드 시간 3",
    "stat.fieldDuration.04": "일반 필드 시간 4",
    "stat.boss.01": "보스 피해 1",
    "stat.boss.02": "보스 피해 2",
    "stat.boss.03": "보스 피해 3",
    "stat.boss.04": "보스 피해 4",
    "stat.boss.05": "보스 피해 5",
    "skill.fireball.damage": "피해량 강화",
    "skill.fireball.radius": "범위 강화",
    "skill.fireball.cooldown": "쿨타임 강화",
    "skill.lightning.damage": "피해량 강화",
    "skill.lightning.radius": "범위 강화",
    "skill.lightning.cooldown": "쿨타임 강화",
    "skill.freeze.damage": "피해량 강화",
    "skill.freeze.radius": "범위 강화",
    "skill.freeze.cooldown": "쿨타임 강화",
    "skill.hurricane.damage": "피해량 강화",
    "skill.hurricane.radius": "범위 강화",
    "skill.hurricane.cooldown": "쿨타임 강화",
    "skill.meteor.damage": "피해량 강화",
    "skill.meteor.radius": "범위 강화",
    "skill.meteor.cooldown": "쿨타임 강화",
    "skill.dragonBreath.damage": "피해량 강화",
    "skill.dragonBreath.radius": "범위 강화",
    "skill.dragonBreath.cooldown": "쿨타임 강화",
    "skill.cursorAura.damage": "피해량 강화",
    "skill.cursorAura.radius": "범위 강화",
    "skill.cursorAura.cooldown": "쿨타임 강화",
    "monster.01.production.01": "생산량 2",
    "monster.01.production.02": "생산량 3",
    "monster.01.production.03": "생산량 4",
    "monster.02.production.01": "생산량 2",
    "monster.02.production.02": "생산량 3",
    "monster.02.production.03": "생산량 4",
    "monster.03.production.01": "생산량 2",
    "monster.03.production.02": "생산량 3",
    "monster.03.production.03": "생산량 4",
    "monster.04.production.01": "생산량 2",
    "monster.04.production.02": "생산량 3",
    "monster.04.production.03": "생산량 4",
    "monster.05.production.01": "생산량 2",
    "monster.05.production.02": "생산량 3",
    "monster.05.production.03": "생산량 4",
    "monster.06.production.01": "생산량 2",
    "monster.06.production.02": "생산량 3",
    "monster.06.production.03": "생산량 4",
    "monster.07.production.01": "생산량 2",
    "monster.07.production.02": "생산량 3",
    "monster.07.production.03": "생산량 4",
    "monster.08.production.01": "생산량 2",
    "monster.08.production.02": "생산량 3",
    "monster.08.production.03": "생산량 4",
    "monster.09.production.01": "생산량 2",
    "monster.09.production.02": "생산량 3",
    "monster.09.production.03": "생산량 4",
    "monster.10.production.01": "생산량 2",
    "monster.10.production.02": "생산량 3",
    "monster.10.production.03": "생산량 4",
    "relic.monster.01.level.01": "숲의 심장 2",
    "relic.monster.01.level.02": "숲의 심장 3",
    "relic.monster.01.level.03": "숲의 심장 4",
    "relic.monster.01.level.04": "숲의 심장 5",
    "relic.monster.02.level.01": "동굴의 송곳니 2",
    "relic.monster.02.level.02": "동굴의 송곳니 3",
    "relic.monster.02.level.03": "동굴의 송곳니 4",
    "relic.monster.02.level.04": "동굴의 송곳니 5",
    "relic.monster.03.level.01": "황금 포자 2",
    "relic.monster.03.level.02": "황금 포자 3",
    "relic.monster.03.level.03": "황금 포자 4",
    "relic.monster.03.level.04": "황금 포자 5",
    "relic.monster.04.level.01": "잔령의 가면 2",
    "relic.monster.04.level.02": "잔령의 가면 3",
    "relic.monster.04.level.03": "잔령의 가면 4",
    "relic.monster.04.level.04": "잔령의 가면 5",
    "relic.monster.05.level.01": "수정 독침 2",
    "relic.monster.05.level.02": "수정 독침 3",
    "relic.monster.05.level.03": "수정 독침 4",
    "relic.monster.05.level.04": "수정 독침 5",
    "relic.monster.06.level.01": "서리 결정 2",
    "relic.monster.06.level.02": "서리 결정 3",
    "relic.monster.06.level.03": "서리 결정 4",
    "relic.monster.06.level.04": "서리 결정 5",
    "relic.monster.07.level.01": "빙결 실타래 2",
    "relic.monster.07.level.02": "빙결 실타래 3",
    "relic.monster.07.level.03": "빙결 실타래 4",
    "relic.monster.07.level.04": "빙결 실타래 5",
    "relic.monster.08.level.01": "불멸의 핵 2",
    "relic.monster.08.level.02": "불멸의 핵 3",
    "relic.monster.08.level.03": "불멸의 핵 4",
    "relic.monster.08.level.04": "불멸의 핵 5",
    "relic.monster.09.level.01": "용의 불씨 2",
    "relic.monster.09.level.02": "용의 불씨 3",
    "relic.monster.09.level.03": "용의 불씨 4",
    "relic.monster.09.level.04": "용의 불씨 5",
    "relic.monster.10.level.01": "고대 왕관 2",
    "relic.monster.10.level.02": "고대 왕관 3",
    "relic.monster.10.level.03": "고대 왕관 4",
    "relic.monster.10.level.04": "고대 왕관 5",
    "relic.boss.01.level.01": "보스 유물 1 2",
    "relic.boss.01.level.02": "보스 유물 1 3",
    "relic.boss.01.level.03": "보스 유물 1 4",
    "relic.boss.01.level.04": "보스 유물 1 5",
    "relic.boss.02.level.01": "보스 유물 2 2",
    "relic.boss.02.level.02": "보스 유물 2 3",
    "relic.boss.02.level.03": "보스 유물 2 4",
    "relic.boss.02.level.04": "보스 유물 2 5",
    "relic.boss.03.level.01": "보스 유물 3 2",
    "relic.boss.03.level.02": "보스 유물 3 3",
    "relic.boss.03.level.03": "보스 유물 3 4",
    "relic.boss.03.level.04": "보스 유물 3 5",
    "relic.boss.04.level.01": "보스 유물 4 2",
    "relic.boss.04.level.02": "보스 유물 4 3",
    "relic.boss.04.level.03": "보스 유물 4 4",
    "relic.boss.04.level.04": "보스 유물 4 5",
    "relic.boss.05.level.01": "보스 유물 5 2",
    "relic.boss.05.level.02": "보스 유물 5 3",
    "relic.boss.05.level.03": "보스 유물 5 4",
    "relic.boss.05.level.04": "보스 유물 5 5",
    "fragment.relic.monster.01": "숲의 심장 1 조각",
    "fragment.relic.monster.02": "동굴의 송곳니 1 조각",
    "fragment.relic.monster.03": "황금 포자 1 조각",
    "fragment.relic.monster.04": "잔령의 가면 1 조각",
    "fragment.relic.monster.05": "수정 독침 1 조각",
    "fragment.relic.monster.06": "서리 결정 1 조각",
    "fragment.relic.monster.07": "빙결 실타래 1 조각",
    "fragment.relic.monster.08": "불멸의 핵 1 조각",
    "fragment.relic.monster.09": "용의 불씨 1 조각",
    "fragment.relic.monster.10": "고대 왕관 1 조각",
    "fragment.relic.boss.01": "보스 유물 1 1 조각",
    "fragment.relic.boss.02": "보스 유물 2 1 조각",
    "fragment.relic.boss.03": "보스 유물 3 1 조각",
    "fragment.relic.boss.04": "보스 유물 4 1 조각",
    "fragment.relic.boss.05": "보스 유물 5 1 조각"
}

def build_reference(document):
    def annotate(value, path="", field=""):
        if isinstance(value, dict):
            result = {}
            for key, child in value.items():
                if key not in LABELS:
                    raise ValueError("Add a Korean field label: " + key)
                result[key + " (" + LABELS[key] + ")"] = annotate(child, path + "." + key, key)
            return result
        if isinstance(value, list):
            return [annotate(child, path + "[" + str(i) + "]", field) for i, child in enumerate(value)]
        explanation = EXPLANATIONS[field]
        if field == "enabled" and ".gemstones[" in path:
            explanation = "현재 활성 몬스터 중 이 젬을 공급하는 종류가 있는지 나타냅니다. 보유량과 독립적이며 최종 생성 단계에서 공급원 기준으로 다시 계산합니다."
        elif field == "enabled" and ".relics[" in path:
            explanation = "유물을 획득했는지 나타냅니다. level이 0보다 클 때 true여야 합니다."
        entry = {"원본값": value, "설명": explanation}
        if isinstance(value, str) and value in TRANSLATIONS:
            entry["한국어뜻"] = TRANSLATIONS[value]
        return entry
    canonical = json.dumps(document, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    return {
        "문서안내": {
            "용도": "전투 정보 기본값의 모든 키·값을 설명하는 한국어 참고서. 실제 게임 입력이나 현재 세이브가 아닙니다.",
            "게임에서사용": False,
            "수정할원본파일": SOURCE.as_posix(),
            "원본SHA256": hashlib.sha256(canonical.encode("utf-8")).hexdigest(),
            "읽는법": "영문키 (한글명) 아래에 원본값과 설명을 표시합니다. 영어 문구·ID의 뜻은 한국어뜻을 참고하세요.",
            "수정주의": "수치 변경은 영어 원본에서만 합니다. 이 파일을 수정해도 게임은 바뀌지 않습니다.",
            "재생성방법": "python3 tools/build_korean_game_data_reference.py --patch 출력을 apply_patch로 적용합니다.",
            "포함범위": "전투 시작 정보의 모든 필드: 스탯·전투 규칙·젬 6종·몬스터 10종과 행동 특성·스킬 7종. 성장 설정은 별도 파일이며 포함하지 않습니다."
        },
        "전체데이터해설": annotate(document)
    }

def decode_reference(value):
    if isinstance(value, list):
        return [decode_reference(child) for child in value]
    if "원본값" in value:
        return value["원본값"]
    return {key.split(" (", 1)[0]: decode_reference(child) for key, child in value.items()}

def build_key_reference(value):
    """Keep every source value and container; translate only object keys."""
    if isinstance(value, dict):
        result = {}
        for key, child in value.items():
            if key not in LABELS:
                raise ValueError("Add a Korean field label: " + key)
            result[key + "(" + LABELS[key] + ")"] = build_key_reference(child)
        return result
    if isinstance(value, list):
        return [build_key_reference(child) for child in value]
    return value

def decode_key_reference(value):
    if isinstance(value, dict):
        return {key.split("(", 1)[0]: decode_key_reference(child)
                for key, child in value.items()}
    if isinstance(value, list):
        return [decode_key_reference(child) for child in value]
    return value

def validate_reference(document):
    actual = json.loads((ROOT / OUTPUT).read_text())
    assert actual == build_reference(document), "Korean reference is stale or incomplete; regenerate it."
    assert decode_reference(actual["전체데이터해설"]) == document, "Reference does not preserve all source values."
    assert actual["문서안내"]["게임에서사용"] is False
    keys = json.loads((ROOT / KEYS_OUTPUT).read_text(encoding="utf-8"))
    # JSON comparison also distinguishes booleans from numbers.
    encode = lambda value: json.dumps(value, ensure_ascii=False, sort_keys=True)
    assert encode(keys) == encode(build_key_reference(document)), "Korean key reference is stale or incomplete."
    assert encode(decode_key_reference(keys)) == encode(document), "Key reference changed source values or types."

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--patch", action="store_true")
    args = parser.parse_args()
    document = json.loads((ROOT / SOURCE).read_text())
    if not args.patch:
        validate_reference(document)
        print("PASS: Korean detailed and key-only references match every English runtime field and value")
        return
    print("*** Begin Patch")
    for output, content in ((OUTPUT, build_reference(document)),
                            (KEYS_OUTPUT, build_key_reference(document))):
        rendered = json.dumps(content, ensure_ascii=False, indent=2) + "\n"
        path = ROOT / output
        if path.exists() and path.read_text(encoding="utf-8") == rendered:
            continue
        if path.exists():
            print("*** Update File: " + output.as_posix())
            print("@@")
            for line in path.read_text(encoding="utf-8").splitlines(): print("-" + line)
        else:
            print("*** Add File: " + output.as_posix())
        for line in rendered.splitlines(): print("+" + line)
    print("*** End Patch")

if __name__ == "__main__":
    main()
